baseURL = "https://genericspecimen.github.io/blog/"
languageCode = "en-us"
title = "A generic blog"
canonifyurls = true
theme = "scratch"
publishDir="docs"
paginate = 10
googleAnalytics = "UA-127407677-1"

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Irfan Sheikh"
    github = "genericSpecimen"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = ""
    instagram = ""

[params]
    tagline = "Yet another blog "
