baseURL = "http://example.org/"
languageCode = "en-us"
title = "genericSpecimen's blog"
canonifyurls = true
theme = "scratch"

paginate = 10

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Irfan Sheikh"
    github = "genericSpecimen"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = ""
    instagram = ""

[params]
    tagline = "Yet another blog "
